### PR TITLE
Apply fixes for netstandard nuget package

### PR DESCRIPTION
**Pull request by ivog**

### CODE REVIEW

**Comment by ivog** [comment]
Attempt to solve #17

**Comment by eiriktsarpalis** [comment]
Great work! I think what's missing is a binding redirect for the new FSharp.Core

**Comment by ivog** [comment]
thanks @eiriktsarpalis this PR is getting a bit sloppy but it seems like the appveyor build is now succeeding

**Comment by eiriktsarpalis** [comment]
I'm working on migrating the project to the new project structure. Would you mind if I cherry-picked your changes and come up with a new PR?

**Comment by ivog** [comment]
@eiriktsarpalis I wouldn't mind at all! Please feel free to do whatever is neccesary to get the netstandard package out there! :)

**Comment by manofstick** [comment]
Subsumed by #22

**Pull request closed without merging**
