### PR TITLE
CoreClr projects files

### PR DESCRIPTION
**Pull request by eloraiby**

### CODE REVIEW

**Comment by eloraiby** [comment]
I am on Linux using coreclr only. Will have to change some scripts as well. Need to check if it will affect building using coreclr.

**Comment by atlemann** [comment]
You could try this to make `dotnet build` use mono for the net461 target. It's a bit old so the might be other ways now though. https://atlemann.github.io/fsharp/2018/03/07/multi-targeting-mono.html

**Comment by atlemann** [comment]
Or this https://stu.dev/dotnet-framework-reference-assemblies-via-nuget/

**Comment by dsyme** [comment]
> Why is this removing net461?

I think it's ok to remove .NET 4.x support and go to .NET Standard 2.0 only in those cases where an existing version of the package exists for .NET 4.x and it is known good and stable 

The recent announcements at build make it pretty clear that .NET Standard and the unified ".NET" are the way forward, and it is best to focus engineering time on that path unless there are really very strong reasons for .NET 4.0-4.6 support.

**Comment by eloraiby** [comment]
So, no support for net461 ?

**Comment by dsyme** [comment]
> So, no support for net461 ?

I don't mind either way. Cut it if it is problematic

**Comment by eiriktsarpalis** [comment]
I believe the changes here have already been addressed by #33. Closing for now.

**Pull request closed without merging**
