### PR TITLE
Support FieldSet expressions

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
Small PR that adds support for `Expr.FieldSet` expressions

### CODE REVIEW

**Comment by dsyme** [comment]
tests?

**Comment by eiriktsarpalis** [comment]
@dsyme done

**Comment by eiriktsarpalis** [comment]
@dsyme FYI the solution doesn't build in 2017 because apparently portable is not supported.

**Comment by dsyme** [comment]
@eiriktsarpalis  PCL are supported, it will be some msbuild problem as always...

**Comment by dsyme** [comment]
@manofstick Would you like to republish the nuget package?  Or @eiriktsarpalis we can make you a co-maintainer?

**Comment by eiriktsarpalis** [comment]
@dsyme sure.

**Comment by manofstick** [comment]
Thanks @eiriktsarpalis, I'm finding it increasingly difficult to dedicate my time to my outstanding open source projects due to family and work commitments.

**Comment by dsyme** [comment]
@eiriktsarpalis You're in https://github.com/fsprojects/FSharp.Quotations.Evaluator/pull/20

**Comment by eiriktsarpalis** [comment]
Thanks. Could you possibly add me as owner in the nuget package as well?

**Comment by dsyme** [comment]
Invitation sent :)

**Comment by eiriktsarpalis** [comment]
👍

**Pull request merged**
