### PR TITLE
Net core support discussion 15

### PR DESCRIPTION
**Pull request by tjaskula**
According to the issue #15 I've added the minimum to generate the netstandard1.6 package.
I build the whole with the `./build.cmd MergeDotnetCoreIntoNuget`. .NET Core NuGet package is added to the original NuGet package.

### CODE REVIEW

**Comment by manofstick** [comment]
Good stuff! I'll hopefully get some time on the weekend to review and pull.

**Comment by enricosada** [comment]
@manofstick i just need to fix portable7 build on travis ci.
seems it doesnt find the `fsharp.core` but is annoying to diagnose why.

**Comment by enricosada** [comment]
opened https://github.com/fsharp/fsharp/issues/759 to track the ubuntu failure, for the moment i configured travis to allow failure just for ubuntu, osx is expected to succeed.

Atm the nupkg generated from mono are not complete, because cannot generate the `.pdb`, but that's the only difference.

so atm `build BuildPackage` will generate the usual nupkg in the normal directory, but with also `netstandard1.6`

**Comment by manofstick** [comment]
@enricosada / @tjaskula 

Do you want this merged now? I'm happy to pull it in. I mean I haven't found time to get this up and going myself, but "Files Changed" are all just support files, so I'm happy we're not screwing with functionality, and existing tests passed...

And then if that's all good, I'll dust off those nuget instructions and then update that...

**Comment by tjaskula** [comment]
@manofstick For me it's ok to do it. However you would need to make run the build.fsx so it can build, generate and mergde the nuget package so you can publish it.

**Comment by enricosada** [comment]
usual `build BuildPackage` will do

**Comment by Horusiath** [comment]
Guys, what's the status of this? Some people (read: Akka.NET team :P ) will need this to move forward.

**Comment by manofstick** [comment]
@Horusiath 

Sorry, I dropped the ball here, but will try to do it now...

**Comment by OlegZee** [comment]
Any update on this?

**Comment by manofstick** [comment]
@eiriktsarpalis 

We're you going to make the nuget package as per #17? (Just wondering as @OlegZee was asking)

**Comment by tjaskula** [comment]
@manofstick I can do the package if this is the only thing left to do.

**Comment by manofstick** [comment]
@dsyme can you give permission to @tjaskula to create the NuGet package? @eiriktsarpalis seems to have been busy, and my homelife is just getting more complicated...

**Comment by dsyme** [comment]
@manofstick @tjaskula Invitation sent

**Comment by tjaskula** [comment]
thanks @dsyme @manofstick. Invitation accepted :)

**Pull request merged**
